import "./globals.css";
import LayoutContent from "./LayoutContent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/MsmeguruLogo.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased bg-white text-gray-900">
        <LayoutContent>{children}</LayoutContent>
      </body>
    </html>
  );
}
